# Generated by Django 3.2.7 on 2021-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
    ]
