# Generated by Django 3.2 on 2024-02-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20240217_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterModelTable(
            name='images',
            table=None,
        ),
    ]
