# Generated by Django 3.2 on 2024-05-14 17:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_auto_20240514_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=tinymce.models.HTMLField(),
        ),
    ]
