# Generated by Django 4.2.13 on 2024-05-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_alter_review_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=100)),
                ('couleurs', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='myshop.product')),
            ],
        ),
    ]
