# Generated by Django 4.2.13 on 2024-06-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
    ]
