# Generated by Django 4.2.13 on 2024-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0017_remove_product_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
