# Generated by Django 4.2.13 on 2024-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0018_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
    ]
