"""
Django settings for LuckyProject project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import braintree
# Build paths inside the project like this: BASE_DIR / 'subdir'.
from braintree import Configuration, Environment

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-lslk@q+e+u3^te@e(2%y8(#8j+p_k-0ywnu9wi672d2s=bcm$v'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart.apps.CartConfig',
    'myshop.apps.MyshopConfig',
    'coupons.apps.CouponsConfig',
    'tinymce',
    'mptt',
    'tailwind',
    'theme',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'django.forms',
    'django_filters',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'account.Customer'

ROOT_URLCONF = 'LuckyProject.urls'

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myshop.context_processors.list_categories',
                'myshop.context_processors.get_featured_products',
                'cart.context_processors.cart',
                'account.context_processors.getLogin',
                'account.context_processors.userRegister',
                'cart.context_processors.AddformCart',

            ],
        },
    },
]

WSGI_APPLICATION = 'LuckyProject.wsgi.application'

ASGI_APPLICATION = "LuckyProject.asgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecommerce_projet',
        'USER': 'ayoub',
        'PASSWORD': "Tabahmout55",
        'PORT': '5433',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

CART_SESSION_ID = 'cart'
EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_ACCESS_KEY_ID = 'AKIAXYKJR3JOJAAJLK4I'
AWS_SECRET_ACCESS_KEY = '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'
CELERY_BROKER_URL = 'amqp://localhost:5672'

BRAINTREE_MERCHANT_ID = 'nc6drc8n7z44njgj'  # Merchant ID
BRAINTREE_PUBLIC_KEY = 'ppq66w4mj3c64mhr'  # Public Key
BRAINTREE_PRIVATE_KEY = '8d9a786ff00c868ed91468fb8ef3ff58'  # Private key

INTERNAL_IPS = [
    "127.0.0.1",
]

BRAINTREE_CONF = Configuration(
    Environment.Sandbox,
    BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "myshop:home"
LOGOUT_REDIRECT_URL = "myshop:home"
LOGIN_URL = "account:login"
TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
