"""
Django settings for LuckyProject project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import braintree
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
from braintree import Configuration, Environment

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DEBUG = env('DEBUG')

SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = ['www.jouetspalace.com', '45.90.123.159', '127.0.0.1','jouetspalace.com']

INSTALLED_APPS = [
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart.apps.CartConfig',
    'myshop.apps.MyshopConfig',
    'coupons.apps.CouponsConfig',
    'social_django',
    'tinymce',
    'mptt',
    'tailwind',
    'theme',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'django.forms',
    'django_filters',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '404060147657-na30qjtg3dcksh1i5lo812po82u6irun.apps.googleusercontent.com'

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

SOCIAL_AUTH_JSONFIELD_ENABLED = True

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'account.Customer'

ROOT_URLCONF = 'LuckyProject.urls'

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myshop.context_processors.list_categories',
                'myshop.context_processors.get_featured_products',
                'myshop.context_processors.newsletter_form',
                'cart.context_processors.cart',
                'account.context_processors.getLogin',
                'account.context_processors.userRegister',
                'cart.context_processors.AddformCart',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'LuckyProject.wsgi.application'

ASGI_APPLICATION = "LuckyProject.asgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('ENGINE'),
        'NAME': env('NAME'),
        'USER': env('USER'),
        'PASSWORD': env('PASSWORD'),
        'HOST': 'localhost',
        'PORT': env('PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CART_SESSION_ID = 'cart'
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
BRAINTREE_MERCHANT_ID = 'nc6drc8n7z44njgj'  # Merchant ID
BRAINTREE_PUBLIC_KEY = 'ppq66w4mj3c64mhr'  # Public Key
BRAINTREE_PRIVATE_KEY = '8d9a786ff00c868ed91468fb8ef3ff58'  # Private key

INTERNAL_IPS = [
    "127.0.0.1",
]

BRAINTREE_CONF = Configuration(
    Environment.Sandbox,
    BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

if DEBUG:
    STATIC_URL='/static/'
    STATICFILES_DIRS=(
        os.path.join(BASE_DIR,'static'),
    )
    MEDIA_URL='/media/'
    MEDIA_ROOT=os.path.join(BASE_DIR,'media')

else:
    STATIC_URL = '/static/'
    STATIC_ROOT = '/var/www/html/static/'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = '/var/www/html/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = "myshop:home"
LOGOUT_REDIRECT_URL = "myshop:home"
LOGIN_URL = "account:login"
TAILWIND_APP_NAME = "theme"
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
