# Generated by Django 3.2.7 on 2021-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default=1112222211, max_length=12, verbose_name='telephone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code_postal',
            field=models.CharField(max_length=20, verbose_name='code postal'),
        ),
    ]
