# Generated by Django 3.2.7 on 2021-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211219_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_paiement',
            field=models.CharField(choices=[('paiement par carte bancaire', 'paiement par carte bancaire'), ('paiement sur livraison', 'paiement sur livraison')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
