# Generated by Django 3.2.7 on 2021-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_type_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_paiement',
            field=models.CharField(choices=[('paiement par carte bancaire', 'paiement par carte bancaire'), ('paiement sur livraison', 'paiement sur livraison')], default='paiement par carte bancaire', max_length=30),
        ),
    ]
