# Generated by Django 3.2 on 2024-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='different_shipping',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
