# Generated by Django 3.2 on 2024-02-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_different_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='different_shipping',
        ),
    ]
