# Generated by Django 3.2 on 2024-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_different_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_paiement',
            field=models.CharField(choices=[('paiement par virement bancaire', 'paiement par virement bancaire'), ('paiement sur livraison', 'paiement sur livraison')], default='paiement par virement bancaire', max_length=30),
        ),
    ]
