# Generated by Django 4.2.13 on 2024-05-23 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addresse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ville',
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=20, verbose_name='code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('addrese', models.CharField(max_length=250, verbose_name='adresse')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=20, verbose_name='code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('addrese', models.CharField(max_length=250, verbose_name='adresse')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address_facturation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='orders.billingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='orders.shippingaddress'),
        ),
    ]
