# Generated by Django 4.2.13 on 2024-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_addresse_remove_order_code_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_facturation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_livraison',
        ),
        migrations.AddField(
            model_name='order',
            name='addresse',
            field=models.CharField(default='', max_length=250, verbose_name='adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='code_postal',
            field=models.CharField(default=1, max_length=20, verbose_name='code postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ville',
            field=models.CharField(default=1, max_length=100, verbose_name='ville'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
